### ISSUE TITLE
lazyvim configuration

### ISSUE THREAD

**Issue by adrien-barret** [kcl-lang/kcl.nvim#6]
Hi there,

I tried the lsp config as mentioned to my lazyvim. atm I don't have a dedicated file to manage lsp as it's built in. Do you have a more complete example ?

Ty,

Ad

**Comment by Peefy** [comment]
Hello @adrien-barret Can the following instructions help you?

Since you're using built-in LSP in Neovim, here's a more complete example of how to configure the KCL language server in your Neovim configuration.

First, ensure that you have the required LSP plugins installed. Then, you can add the following configuration to your init.vim or init.lua file:

For init.vim (Vimscript):

```shell
lua << EOF
lvim.lsp.servers = {
  kcl = {
    on_attach = on_attach, -- your custom on_attach function
    filetypes = { "kcl" },
    root_dir = util.root_pattern(".git"),
  },
}
EOF
```

For init.lua (Lua):

```lua
require('lspconfig').kcl.setup{
  on_attach = on_attach, -- your custom on_attach function
  filetypes = { "kcl" },
  root_dir = require('lspconfig.util').root_pattern(".git"),
}
```

Replace `on_attach` with your custom on_attach function if you have one.

This configuration will set up the KCL language server to work with Neovim's built-in LSP. It specifies that the language server should be used for files with the filetype "kcl" and sets the root directory for the language server.

Ensure that you have the necessary lspconfig and util modules imported in your Lua configuration file if you're using Lua. If you're using Vimscript, you don't need to worry about this as Vimscript doesn't have separate module imports.

I hope this example helps. If you have any further questions or need additional assistance, feel free to ask!

**Comment by eshepelyuk** [comment]
Hello

I am using this code snippet 

```lua
local server_config = require("lspconfig.configs")
local util = require("lspconfig.util")

server_config.kcl = {
	default_config = {},
}

require("lspconfig").kcl.setup({
	cmd = { "kcl-language-server" },
	filetypes = { "kcl" },
	root_dir = util.root_pattern(".git"),
})
```

But I notice that language server is run when opening any file, not only `*.k`

PS: i am not using LazyVim, but `vim-plug`  instead.

**Comment by Peefy** [comment]
fyi @He1pa

**Comment by He1pa** [comment]
> Hello
> 
> I am using this code snippet
> 
> ```lua
> local server_config = require("lspconfig.configs")
> local util = require("lspconfig.util")
> 
> server_config.kcl = {
> 	default_config = {},
> }
> 
> require("lspconfig").kcl.setup({
> 	cmd = { "kcl-language-server" },
> 	filetypes = { "kcl" },
> 	root_dir = util.root_pattern(".git"),
> })
> ```
> 
> But I notice that language server is run when opening any file, not only `*.k`
> 
> PS: i am not using LazyVim, but `vim-plug` instead.

I don't know very clear about `vim-plug`, but according to the documentation, the configuration maybe

~/.config/nvim/init.vim for Neovim
```
call plug#begin()

Plug('kcl-lang/kcl.nvim')

call plug#end()
```

or ~/.config/nvim/init.lua for Neovim
```
local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('kcl-lang/kcl.nvim', { ['for'] = 'kcl' })

vim.call('plug#end')
```

But after I configured it like this, only the Diagnostic work, 
![image](https://github.com/user-attachments/assets/9f6cce39-0519-4e45-adf2-8d24c6307b57)

but there was no goto definition/completion or other capbilities. If you have any suggestions, I will update the configuration of vim-plug in README.

**Comment by eshepelyuk** [comment]
Hello, 
The plugin behavior must be independent of the plugin manager used to install that plugin.
So, there's no need to play with `vim-plug` settings, this plugin should itself understand when it should be executed,
regardless of the plugin manager.

So, the idea, that plugin load should be handled by `lsp-config` and be independent of `LazyVim` usage.

**Comment by He1pa** [comment]
Agreed. But I think ft (file type) is a setting `be independent of the plugin manager`.  And after my test, vim-plug will not start kcl plugins in other files when using the configuration I provided above. Can you provide more information?

**Comment by eshepelyuk** [comment]
> Agreed. But I think ft (file type) is a setting `be independent of the plugin manager`. And after my test, vim-plug will not start kcl plugins in other files when using the configuration I provided above. Can you provide more information?

I don't understand which additional information you're requesting :(
Plugin currently depends on `LazyVim` to be properly started, this should be changed and plugin should rely on `lspconfig` to start an LSP server and be independent of the plugin manager.

**Comment by He1pa** [comment]
For example, the screenshot of the plugin being started in other files. In addition, in your configuration, I did not see that you installed the kcl plugin

**Comment by eshepelyuk** [comment]
> For example, the screenshot of the plugin being started in other files. In addition, in your configuration, I did not see that you installed the kcl plugin

![image](https://github.com/user-attachments/assets/3cd0c33a-289f-4cd2-a84f-b2b9fc42a112)

**Comment by He1pa** [comment]
Ok, I have understood and reproduced the problem

**Comment by He1pa** [comment]
I find in `vim-plug`, This config is enough. And dont need to config with `lsp-config`
```
local vim = vim
local Plug = vim.fn['plug#']
vim.call('plug#begin')
Plug('kcl-lang/kcl.nvim', { ['for'] = 'kcl' })
vim.call('plug#end')
```

` { ['for'] = 'kcl' }` is required, otherwise the phenomenon you mentioned will occur

**Comment by eshepelyuk** [comment]
@He1pa but this is not a solution, to the core problem - this plugin dependency on configuration of particular plugin manager.
What if one uses packer, lua rocks etc ?

Instead, the plugin should be independent on which plugin manager is used, and either handle opening in certain filetypes itself, or, more preferable and unified, depend on `nvim-lspconfig` - as other LSP do.

Currently, this plugin works without `nvim-lspconfig`, because it starts LSP server itself and depends on certain plugin manager configuration to be applied for certain filetype (`kcl`).

**Comment by eshepelyuk** [comment]
Created an new issue #11 related to `nvim-lspconfig` and various plugin managers
